# 1. Используем официальный образ Node.js
FROM node:22

# 2. Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# 3. Копируем файлы package.json и package-lock.json
COPY package*.json ./
COPY .npmrc ./

# 4. Устанавливаем зависимости
RUN npm ci

# 5. Копируем все файлы в контейнер
COPY prisma ./prisma
COPY tsconfig*.json ./

# 6. Устанавливаем переменную окружения для Docker
ENV NODE_ENV=development

# 7. Устанавливаем зависимость для ожидания загрузки БД
RUN apt-get update && apt-get install -y wait-for-it

